#!/usr/bin/env python3
"""Makes the in-game menu's font (port/linux/src/menu_font.c): the printable ASCII
characters of Noto Sans (SIL Open Font License) in one anti-aliased 8-bit atlas, plus each character's advance and a solid block for the menu's
rectangles.

The data are 32-bit words, not bytes: the Android build passes the guest's assembly
through tools/android_asm_convert.py, which garbles a long byte array (see
tools/embed_assets.py, which does the same for the HUD's images).

    python tools/menu_font.py [--font /usr/share/fonts/noto/NotoSans-Regular.ttf]

The atlas has COLUMNS cells per row; cell 0 is the solid block, then the
characters from ' ' (32) to '~' (126).
"""

import argparse
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "port/linux/src/menu_font.c"
SIZE = 36            # the font's pixel size in the atlas
MARGIN = 10          # clear pixels all round each glyph, so that filtering never reaches its neighbour
CELL_W, CELL_H = 56, 72   # the widest glyph (W) plus both margins; the line's height plus both margins
COLUMNS = 16
FIRST, LAST = 32, 126


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", default="/usr/share/fonts/noto/NotoSans-Regular.ttf")
    arguments = parser.parse_args()
    font = ImageFont.truetype(arguments.font, SIZE)
    glyphs = LAST - FIRST + 1
    cells = glyphs + 1
    rows = (cells + COLUMNS - 1) // COLUMNS
    atlas = Image.new("L", (COLUMNS * CELL_W, rows * CELL_H), 0)
    draw = ImageDraw.Draw(atlas)
    # cell 0: solid, with a one pixel margin so that filtering never reads a neighbour
    draw.rectangle((2, 2, CELL_W - 3, CELL_H - 3), fill=255)
    advances = []
    ascent, _ = font.getmetrics()
    for index in range(glyphs):
        cell = index + 1
        x, y = (cell % COLUMNS) * CELL_W, (cell // COLUMNS) * CELL_H
        character = chr(FIRST + index)
        advances.append(round(font.getlength(character)))
        draw.text((x + MARGIN, y + MARGIN), character, font=font, fill=255)
    data = atlas.tobytes()
    padded = data + b"\0" * (-len(data) % 4)
    words = struct.unpack("<%dI" % (len(padded) // 4), padded)
    lines = [
        "/* generated by tools/menu_font.py from Noto Sans (SIL Open Font License 1.1): do not edit */",
        "",
        '#include "game_menu.h"',
        "",
        f"const int game_menu_font_size = {SIZE};",
        f"const int game_menu_font_cell_width = {CELL_W};",
        f"const int game_menu_font_cell_height = {CELL_H};",
        f"const int game_menu_font_margin = {MARGIN};",
        f"const int game_menu_font_columns = {COLUMNS};",
        f"const int game_menu_font_first = {FIRST};",
        f"const int game_menu_font_last = {LAST};",
        f"const int game_menu_font_atlas_width = {atlas.width};",
        f"const int game_menu_font_atlas_height = {atlas.height};",
        f"const unsigned long game_menu_font_atlas_size = {len(data)}UL;",
        "const int game_menu_font_advances[] = {" + ", ".join(str(a) for a in advances) + "};",
        f"const unsigned int game_menu_font_atlas[{len(words)}] =",
        "{",
    ]
    for start in range(0, len(words), 8):
        lines.append("\t" + ", ".join("0x%08x" % w for w in words[start:start + 8]) + ",")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines))
    print(f"{OUT.relative_to(ROOT)}: atlas {atlas.width}x{atlas.height}, {len(data)} bytes")


if __name__ == "__main__":
    main()
